name: pq_toast
description: A simple package to show toast message on the web ,support flutter web
version: 0.0.2
author: Mohamed dawood <mo.ah.dawood@gmail.com>
homepage: https://github.com/mo-ah-dawood/pq_toast

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:

